version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: student_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql  

  app:
    build: .
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/student_db
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    stdin_open: true
    tty: true

volumes:
  mysql_data: